[workspace]
resolver = "2"
members = [
    "crates/distributed-client",
    "crates/distributed-server",
    "crates/models",
]

[workspace.dependencies]
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
