[package]
name = "distributed-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
models = { path = "../models" }
bincode = { workspace = true }
